sudo: required
language: go

services:
  - docker
  - mongodb

env:
  global:
    - NAME=yukid
  matrix:
    - GOOS=linux GOARCH=amd64

go:
  # sync.Map introduced in Go 1.9
  - 1.9.x
  - 1.10.x
  - 1.11.x

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/golang/lint/golint
install:
  - dep ensure

before_script:
  - docker pull ustcmirror/test
script:
  - ci/script.sh

before_deploy:
  - ci/build.sh
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: $NAME-*.tar.gz
  api_key:
    secure: BQAJgKCruMRV9LhtWZxtc1wYlTp7Y6CLJFIAn6RhXLUzdtCYJ6kYFiT7ymmspR26QvwzPjRUBYXHmf+Tag+VObEZmuTjoDM9G1qgvft1mr5Fi/9UVEkkgbiZ0O84pakrjBJoR0lXEdyzlAM0tiAOZqym3KPjSfsnLv0ByZkJadcEmNj549Ts6k4RfXgX/HlCkqAwbdu4g3UW8r3+1Ai7BKUofsSRlKuHCfwG427lpsg913QUrdcgEIpXdFDUbAwRkDsYyRqGRnK4X9YvU0MySNA1sSKhBzTgXhb1rAHMq2HKa/ZIpe4Jft0OLu0ZU2hlOK1hd5zS5bRspW/wPV2jZjO+xqWnQNZALOez2Xc53m/vZ8wxipXAdsgSpB81A03Dr7ZLm7SZcVUOGoEcDjRE2RU2k/WzOJ/jP7hNKGEdRWwodzWeczKg+fP69ErolvRFnuCy5IZytYr+4B+0jMKMQsSc0s2DCulV24f8lSKalED1O/Con5zE4rp1ZDurhHNvUKSPxCTEIqlCsbwl+dsYijrb7KyadXZjl6G1QmvIAE02mkQ0y+ALrnZMnfAvLZ5OIPk4V8lBoT6p/xf1foYCRQHfhO2ImhMM0y+7cQDeHLXSDi5VWChxuwUUicNyUB3/eZoJSS8XE8t5H2QC515gs3Qs/KWB8D/5Z3e0ZJEB5i4=
  on:
    tags: true
    condition: $TRAVIS_GO_VERSION = master
    branch: master

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
